server:
  port: 8335

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: @profiles.active@

igferry:
  kafka:
    servers: 127.0.0.1:9092
    producerTopic: igferry-gateway-deliver
    consumerTopic: igferry-gateway-back-
    pollTimeout: 3000
    timeout: 60000
  zookeeper:
    zkServer: 127.0.0.1:2181
    prefixZkPath: /igferry

